services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
        - app
    ports:
      - 9000:9000
    depends_on:
      - db

  queue-worker:
    build:
      context: ./laravel-best
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - app
    depends_on:
      - db
    command: php artisan queue:work
  
  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./laravel-best:/var/www/html
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - app
    depends_on:
      - app

  db:
    image: postgres:17-alpine
    container_name: task_al
    env_file:
      - ./.env
    ports:
      - "2345:5432"
    restart: always
    networks:
      - app

  redis:
    image: bitnami/redis:7.2
    platform: linux/amd64
    ports:
      - 6379:6379
    restart: always
    # volumes:
    #   - redis-data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - app

networks:
  app: