services:
  db:
    image: postgres:17-alpine
    container_name: task_al_db
    env_file:
      - ./.env
    ports:
      - "2345:5432"
    restart: always
    networks:
      - app

networks:
  app: