services:
  database:
    image: postgres:17-alpine
    container_name: task_al
    env_file:
      - ../.db.env
    ports:
      - "2345:5432"
    restart: always
    networks:
      - app

networks:
  app: